from __future__ import annotations

from datetime import datetime, timezone

SEED_EVENTS = [
    {
        "id": "evt-fastapi",
        "source": "sample-rss",
        "title": "FastAPI Deep Dive: Building Production APIs",
        "description": "A hands-on backend workshop covering auth, async routes, testing, and deployment hygiene.",
        "city": "Bangalore",
        "venue": "Indiranagar Dev Hub",
        "lat": 12.9784,
        "lon": 77.6408,
        "topic": "tech",
        "event_date": "2026-06-06T10:00:00+00:00",
    },
    {
        "id": "evt-jazz",
        "source": "sample-scrape",
        "title": "Rooftop Jazz Evening",
        "description": "A small-format jazz trio session with coffee, food popups, and open seating.",
        "city": "Bangalore",
        "venue": "Church Street Social",
        "lat": 12.9759,
        "lon": 77.6037,
        "topic": "music",
        "event_date": "2026-06-04T14:30:00+00:00",
    },
    {
        "id": "evt-ai-design",
        "source": "sample-reddit",
        "title": "AI for Designers Lightning Talks",
        "description": "Designers and engineers share practical workflows for prototyping with local AI tools.",
        "city": "Bangalore",
        "venue": "Koramangala Creative Lab",
        "lat": 12.9352,
        "lon": 77.6245,
        "topic": "tech",
        "event_date": "2026-06-08T12:00:00+00:00",
    },
    {
        "id": "evt-cleanup",
        "source": "sample-rss",
        "title": "Cubbon Park Community Cleanup",
        "description": "Volunteer morning for park cleanup, civic mapping, and neighborhood coordination.",
        "city": "Bangalore",
        "venue": "Cubbon Park Bandstand",
        "lat": 12.9763,
        "lon": 77.5929,
        "topic": "community",
        "event_date": "2026-06-07T03:30:00+00:00",
    },
    {
        "id": "evt-film",
        "source": "sample-scrape",
        "title": "Short Film Screening: New Indian Voices",
        "description": "Independent short films followed by a filmmaker Q&A and community discussion.",
        "city": "Bangalore",
        "venue": "Suchitra Cinema",
        "lat": 13.0358,
        "lon": 77.5581,
        "topic": "film",
        "event_date": "2026-06-10T13:30:00+00:00",
    },
    {
        "id": "evt-python-chennai",
        "source": "sample-reddit",
        "title": "Python Data Apps Mini Bootcamp",
        "description": "Build small dashboards with Python, SQLite, and browser-native charts.",
        "city": "Chennai",
        "venue": "T Nagar Maker Space",
        "lat": 13.0418,
        "lon": 80.2341,
        "topic": "tech",
        "event_date": "2026-06-05T09:30:00+00:00",
    },
    {
        "id": "evt-food-chennai",
        "source": "sample-rss",
        "title": "Filter Coffee and Baking Pop-Up",
        "description": "Local bakers and roasters run a tasting afternoon with recipe swaps.",
        "city": "Chennai",
        "venue": "Mylapore Courtyard",
        "lat": 13.0339,
        "lon": 80.2687,
        "topic": "food",
        "event_date": "2026-06-09T10:30:00+00:00",
    },
    {
        "id": "evt-delhi-art",
        "source": "sample-scrape",
        "title": "Public Art Walk: Lodhi Murals",
        "description": "Guided walk through public murals with notes on street art and urban history.",
        "city": "Delhi",
        "venue": "Lodhi Art District",
        "lat": 28.5843,
        "lon": 77.2209,
        "topic": "art",
        "event_date": "2026-06-06T04:30:00+00:00",
    },
    {
        "id": "evt-standup",
        "source": "sample-rss",
        "title": "Indie Standup Open Mic",
        "description": "New comics test short sets in a relaxed room with community voting.",
        "city": "Delhi",
        "venue": "Hauz Khas Basement",
        "lat": 28.5494,
        "lon": 77.2001,
        "topic": "comedy",
        "event_date": "2026-06-11T14:00:00+00:00",
    },
    {
        "id": "evt-yoga",
        "source": "sample-reddit",
        "title": "Sunrise Yoga and Mobility Session",
        "description": "Beginner-friendly fitness session focused on mobility, breathing, and recovery.",
        "city": "Delhi",
        "venue": "Nehru Park",
        "lat": 28.5912,
        "lon": 77.1950,
        "topic": "sports",
        "event_date": "2026-06-03T01:30:00+00:00",
    },
    {
        "id": "evt-mumbai-founder",
        "source": "sample-news",
        "title": "Mumbai Founder Mixer: SaaS and Fintech Operators",
        "description": "Early founders trade notes on hiring, fundraising, and product-led growth.",
        "city": "Mumbai",
        "venue": "BKC Startup Loft",
        "lat": 19.0607,
        "lon": 72.8676,
        "topic": "startups",
        "event_date": "2026-06-12T12:30:00+00:00",
    },
    {
        "id": "evt-pune-career",
        "source": "sample-rss",
        "title": "Resume Roast for Product and Engineering Roles",
        "description": "A practical career clinic with mock interviews and portfolio feedback.",
        "city": "Pune",
        "venue": "Baner Community Workspace",
        "lat": 18.5590,
        "lon": 73.7868,
        "topic": "career",
        "event_date": "2026-06-13T08:30:00+00:00",
    },
    {
        "id": "evt-hyderabad-gaming",
        "source": "sample-reddit",
        "title": "Hyderabad Indie Games and Esports Night",
        "description": "Local game dev demos, Valorant brackets, and board game tables.",
        "city": "Hyderabad",
        "venue": "Madhapur Arena",
        "lat": 17.4483,
        "lon": 78.3915,
        "topic": "gaming",
        "event_date": "2026-06-14T11:30:00+00:00",
    },
    {
        "id": "evt-kolkata-news",
        "source": "sample-news",
        "title": "Kolkata Civic Tech Briefing",
        "description": "Community reporters and builders discuss metro updates, public data, and local policy.",
        "city": "Kolkata",
        "venue": "Park Street Civic Lab",
        "lat": 22.5546,
        "lon": 88.3520,
        "topic": "news",
        "event_date": "2026-06-10T10:00:00+00:00",
    },
    {
        "id": "evt-ahmedabad-finance",
        "source": "sample-rss",
        "title": "Fintech and Investing Roundtable",
        "description": "A beginner-friendly session on markets, fintech products, and responsible investing.",
        "city": "Ahmedabad",
        "venue": "Navrangpura Business Center",
        "lat": 23.0365,
        "lon": 72.5611,
        "topic": "finance",
        "event_date": "2026-06-15T12:00:00+00:00",
    },
    {
        "id": "evt-kochi-wellness",
        "source": "sample-scrape",
        "title": "Mindfulness, Mobility, and Coastal Walk",
        "description": "Small-group wellness morning with breathwork, mobility drills, and a slow walk.",
        "city": "Kochi",
        "venue": "Fort Kochi Beach",
        "lat": 9.9658,
        "lon": 76.2421,
        "topic": "wellness",
        "event_date": "2026-06-16T01:30:00+00:00",
    },
    {
        "id": "evt-jaipur-art",
        "source": "sample-scrape",
        "title": "Jaipur Block Print and Illustration Jam",
        "description": "Artists and designers explore textile motifs, sketching, and hands-on printing.",
        "city": "Jaipur",
        "venue": "C-Scheme Design Studio",
        "lat": 26.9128,
        "lon": 75.7873,
        "topic": "art",
        "event_date": "2026-06-17T09:00:00+00:00",
    },
    {
        "id": "evt-remote-ai-news",
        "source": "sample-news",
        "title": "Remote Briefing: AI Policy and Open Models",
        "description": "A live online discussion on AI regulation, model releases, and developer impact.",
        "city": "Remote",
        "venue": "Online",
        "lat": 20.5937,
        "lon": 78.9629,
        "topic": "news",
        "event_date": "2026-06-18T13:30:00+00:00",
        "kind": "news",
    },
]


DEFAULT_PROFILE = {
    "user_id": "demo",
    "city": "Bangalore",
    "radius_km": 25,
    "interests": {"tech": 1.0, "education": 0.65, "music": 0.35},
    "context": {
        "domain": "builder",
        "goal": "Find high-signal local events and news",
        "signal_types": ["event", "news", "signal", "discussion"],
        "freshness": "balanced",
    },
}


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()
